spring:
  application:
    name: email-service

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-mb.yml
      - classpath:application-logging.yml
      - classpath:application-actuator.yml

  mail:
    # Данные почтового клиента
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${SUPPORT_EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          # Шифрование TLS
          starttls:
            enable: ${EMAIL_TLS}
            required: ${EMAIL_TLS}
          # Доверять сертификату почтового клиента
          ssl:
            trust: ${EMAIL_HOST}

server:
  port: 8081
  address: 0.0.0.0
